###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

  php:
    build: .
    container_name: cnab-reader-php
    ports:
    - "8001:80"
    tty: true
    volumes:
    - .:/var/www/html
    - static-content:/tmp/xdebug
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal remote_port=9000 remote_enable=1 profiler_enable_trigger=1 profiler_output_dir=/tmp/xdebug
      APPLICATION_ENV: development

  webgrinder:
    build: ./webgrinder
    container_name: webgrinder
    ports:
      - "8001:80"
    tty: true
    volumes:
      - static-content:/tmp/xdebug

volumes:
  static-content: